action_dim: 1
annealing: true
annealing_start: 0
annealing_steps: 100000
baseline_path: weights.pt
baseline_temp: 0.2
batch: false
count_param: 0.2
dataset_path: dataset/10000/123/1_0/counts_dataset.pkl
dataset_size: 1000
ddqn: true
device: cpu
domain: gym
helicopter_a_max: 1
helicopter_log: false
helicopter_noise: 0.025
helicopter_noise_v: 0.05
helicopter_size: 3
helicopter_time_step: 0.1
helicopter_v_max: 1
episode_max_len: 200
epsilon: 1
extra_stochasticity: 0.0
final_epsilon: 0.01
folder_location: ./baseline/
folder_name: cartpole
game_name: CartPole-v0
gamma: 0.9
history_len: 1
is_learning: true
is_testing: true
kappa: 0.003
learning_frequency: 1
learning_rate: 0.00025
learning_type: regular
max_start_nullops: 0
minibatch_size: 32
minimum_count: 0
nb_actions: 2
network_path: weights.pt
network_size: dense
noise_factor: 1
normalize: 1.0
num_epochs: 30
num_experiments: 1
passes_on_dataset: 2000
replay_max_size: 1000000
replay_min_size: 1
reward_dim: 1
seed: 123
state_shape: [4]
steps_per_epoch: 3000
steps_per_test: 20000
test: false
test_epsilon: 0
update_freq: 1000
